#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Firebase Bridge Node Executable
ROS 2 Firebase Bridge の実行エントリーポイント
"""

import sys
from ros2_firebase_bridge.firebase_bridge_node import main

if __name__ == '__main__':
    sys.exit(main())